// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LunavexCQRS;

internal sealed partial class Vsix
{
    public const string Id = "LunavexCQRS.53639516-5154-4dfe-b2b5-79eb3251d6f0";
    public const string Name = "LunavexCQRS";
    public const string Description = @"Empty VSIX Project.";
    public const string Language = "en-US";
    public const string Version = "1.0";
    public const string Author = "ramazan kurt";
    public const string Tags = "";
}
