// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LunavexCQRS;

using System;

/// <summary>
/// Helper class that exposes all GUIDs used across VS Package.
/// </summary>
internal sealed partial class PackageGuids
{
    public const string LunavexCQRSString = "394bce67-428a-4193-9557-20661862251b";
    public static Guid LunavexCQRS = new Guid(LunavexCQRSString);
}
/// <summary>
/// Helper class that encapsulates all CommandIDs uses across VS Package.
/// </summary>
internal sealed partial class PackageIds
{
    public const int MyMenuGroup = 0x0001;
    public const int MyCommand = 0x0100;
}